version: '2'
services:
    blog1-app:
        image: blog1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blog1-mysql:3306/blog1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog1-mysql:
        extends:
            file: mysql.yml
            service: blog1-mysql
